### ISSUE TITLE
BUG chunked uploads seem to have an undefined response

### ISSUE THREAD

**Issue by muskie9** [bigfork/silverstripe-dropzone#11]
In doing a bit of digging I found that the following only seemed to work for smaller uploads that did not get chunked:
```js
    dropzone.on('success', (file, response) => {
      addHiddenInput(file, response[0]);
    });
```

Updating the logic to the following accesses the response in a different way:
```js
    dropzone.on('success', (file, response) => {
      if (file.upload.chunked) {
        addHiddenInput(file, JSON.parse(file.xhr.response)[0]);
      } else {
        addHiddenInput(file, response[0]);
      }
    });
```

My only thought on why the response in the first case would be undefined is there are multiple requests for the chunk upload. If the js receives the response of any request other than the last one, the response would be empty, causing an issue when trying to add the hidden input.

Admittedly I don't use FE build tools a whole lot so it took a bit to get things compiling to test it. I'm happy to open a PR but I may need some guidance as I did see there was a note in the contributing section of the readme about removing some lines from a the dropzone file before building.

**Comment by lozcalver** [comment]
Hmm, yes it’s "by design" for the responses for chunked uploads to be empty: they should be empty until the final chunk has been uploaded, then it should respond with the file ID: https://github.com/bigfork/silverstripe-dropzone/blob/master/src/DropzoneFileUploadReceiver.php#L128-L137

Is the success handler triggering too early with an empty response? Or is `response` always empty, even when the final chunk has been uploaded?

**Comment by muskie9** [comment]
The `DropzoneFileUploadReceiver` snippet you pointed out seems to be consistent with what I was seeing, so working as expected. From what I could tell the final chunk's `response` is correct and has data, so my best guess would be the `success` handler is most likely triggering too early.

**Comment by lozcalver** [comment]
In that case, I wonder if a simpler fix might be something like this?

```js
if (!response) {
    return;
}
```

If the success handler is being fired when it shouldn’t be, it’s probably better to just ignore it until we know the file has finished uploading. Thanks for looking at this!

**Comment by muskie9** [comment]
For sure, figured that would probably be the way to go. I’ll update the PR after I test a bit.

**Comment by muskie9** [comment]
That totally did the trick. I've updated the PR with the new logic.
