### ISSUE TITLE
BUG no "_config" directory, or "_config.php" file causes module to not be detected

### ISSUE THREAD

**Issue by muskie9** [bigfork/silverstripe-dropzone#13]
It looks like in commit 19365390e4f101fc6a86aa0233400061b5946514 the `_config/config.yml` was removed effectively causing the module to not be detected as a Silverstripe module. This came up as the `vendor-expose` command doesn't detect the module anymore.

**Comment by lozcalver** [comment]
That’s strange, `vendor-expose` should look at `composer.json`, spot the `expose` directive and work from that - `config.yml`/`_config.php` shouldn’t affect it 😕

**Comment by lozcalver** [comment]
Meh, an empty config dir won’t do any harm anyway so let’s merge

**Comment by muskie9** [comment]
I thought so too but found in the vendor plugin module it checks for those. I suppose similar to how SS ignores directories unless either config option is present.
